function out = Polynomial2D3Od(X)
    N = numel(X)/2;
    X = reshape(X,N,2);
    out = zeros(N,10,2);
    out(:,:,1) = [zeros(N,1) ones(N,1) zeros(N,1)  ...
        2*X(:,1) X(:,2) zeros(N,1) ...
        3*X(:,1).^2 2*X(:,1).*X(:,2) X(:,2).^2 zeros(N,1)];
    out(:,:,2) = [zeros(N,2) ones(N,1) ...
        zeros(N,1) X(:,1) 2*X(:,2) ...
        zeros(N,1) X(:,1).^2 2*X(:,1).*X(:,2)  3*X(:,2).^2];
end